apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
  labels:
    app: urlshortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - name: urlshortener
        image: us-west2-docker.pkg.dev/urlshortener-459015/ronak-repo/demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: password
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: db_name
            value: learning
          - name: MYSQL_SERVICE_HOST
            value: mysql