apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      name: website
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: us-west2-docker.pkg.dev/urlshortener-459015/ronak-repo/ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      